<?php

namespace AppBundle\Repository;

/**
 * FlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatRepository extends \Doctrine\ORM\EntityRepository
{
}
