<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Flat;

/**
 * FlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function isExist(Flat $flat)
    {
        //  $em = $this->getEntityManager();
        $dql = $this->_em->createQuery('
            SELECT f
            FROM AppBundle:Flat f
            WHERE f.name LIKE :name
        ')
            ->setMaxResults(1)
            ->setParameter('name', $flat->getName());

        $result = $dql->getOneOrNullResult();
        return $result;
    }
}
