<?php

namespace AppBundle\Repository;

/**
 * RentingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentingRepository extends \Doctrine\ORM\EntityRepository
{
}
