<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;


/**
 * FosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class UserRepository extends EntityRepository
{
    /**
     * @param $user
     * @return int
     */
    public function isExist(User $user)
    {
      //  $em = $this->getEntityManager();
        $dql = $this->_em->createQuery('
            SELECT u.username
            FROM AppBundle:User u
            WHERE u.username LIKE :username
            OR u.email LIKE :email
        ')
            ->setMaxResults(1)
            ->setParameter('username', $user->getUSername())
            ->setParameter('email', $user->getEmail());



        $result = $dql->getOneOrNullResult();
        return $result;
    }
}
