<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * FosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class UserRepository extends EntityRepository
{
    /**
     * @param $user
     * @return int
     */
    public function isExist($user)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('count(p)');
        $dql->from('AppBundle.User', 'p');
        $dql->where($dql->expr()->eq('p', $user));
        return $dql->getQuery()->execute();
    }
}
